#!/usr/bin/env bash

if [[ -n $ENV_HELP ]]; then
    printf "\e[36mshows docker logs: \n  > \e[36;1m$ENV_COMMAND logs [arguments]\e[0m\n"
else
    cd $ENV_PATH
    docker-compose logs $*
    printf "\n"
fi
