#!/usr/bin/env bash

exec_command() {
    if [[ -z "$1" ]]; then
        printf "\e[31mno 'ng' command specified\e[0m\n"
        exit 1
    fi
    cd $ENV_PATH
    docker-compose exec --user=$UID angular node_modules/.bin/ng $*
}

if [[ -n $ENV_HELP ]]; then
    printf "\e[36mruns 'ng' inside the the angular container: \n  > \e[36;1m$ENV_COMMAND angular <commands>\e[0m\n"
else
    exec_command $*
    printf "\n"
fi
