version: '3'

services:

  eventstore:
    image: eventstore/eventstore
    ports:
      - 1113:1113
      - 2113:2113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=${EVENTSTORE_RUN_PROJECTIONS:-all}
      - EVENTSTORE_START_STANDARD_PROJECTIONS=${EVENTSTORE_START_STANDARD_PROJECTIONS:-True}
